[tool.poetry]
name = "ec2-saver"
version = "0.1.0"
description = ""
authors = ["Tomohiko Ozawa <kota65535@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.13.0"
boto3 = "1.35.48"
pytz = "2022.7.1"

[tool.poetry.group.dev.dependencies]
black = "22.12.0"
isort = "5.13.2"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
line_length = 119

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
